services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/?authSource=admin
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    networks:
      - api-network
    depends_on:
      - mongodb
      - redis